# Generated by Django 4.2 on 2023-04-27 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drug',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
