# Generated by Django 4.2 on 2023-04-27 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_drug_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='amount',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='receipt',
            name='times',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
