# Generated by Django 4.2 on 2023-04-30 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_receipt_amount_receipt_times'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='times',
        ),
        migrations.AddField(
            model_name='receiptschedule',
            name='amount',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
